# Generated by Django 3.1.4 on 2020-12-29 22:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('rank', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadevelop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Post Title', max_length=500)),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('the_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('release_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_cover', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('url', models.SlugField(max_length=500, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadevelop.category')),
                ('tag', models.ManyToManyField(to='fadevelop.Tag')),
            ],
        ),
    ]
